//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libMutuales2020.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libMutuales2020.Recursos.Sp", typeof(Sp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spEgresoInsertar.
        /// </summary>
        internal static string spEgresoInsertar {
            get {
                return ResourceManager.GetString("spEgresoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spIngresoInsertar.
        /// </summary>
        internal static string spIngresoInsertar {
            get {
                return ResourceManager.GetString("spIngresoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spVentaInsertar.
        /// </summary>
        internal static string spVentaInsertar {
            get {
                return ResourceManager.GetString("spVentaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspVentaConsultar.
        /// </summary>
        internal static string uspVentaConsultar {
            get {
                return ResourceManager.GetString("uspVentaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspVentaDetalleConsultar.
        /// </summary>
        internal static string uspVentaDetalleConsultar {
            get {
                return ResourceManager.GetString("uspVentaDetalleConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspVentaEliminar.
        /// </summary>
        internal static string uspVentaEliminar {
            get {
                return ResourceManager.GetString("uspVentaEliminar", resourceCulture);
            }
        }
    }
}
