//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libMutuales2020.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sp() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libMutuales2020.Recursos.Sp", typeof(Sp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spEgresoEliminar.
        /// </summary>
        internal static string spEgresoEliminar {
            get {
                return ResourceManager.GetString("spEgresoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spEgresoInsertar.
        /// </summary>
        internal static string spEgresoInsertar {
            get {
                return ResourceManager.GetString("spEgresoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spIngresoEliminar.
        /// </summary>
        internal static string spIngresoEliminar {
            get {
                return ResourceManager.GetString("spIngresoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spIngresoInsertar.
        /// </summary>
        internal static string spIngresoInsertar {
            get {
                return ResourceManager.GetString("spIngresoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spNuevoAno.
        /// </summary>
        internal static string spNuevoAno {
            get {
                return ResourceManager.GetString("spNuevoAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spVentaInsertar.
        /// </summary>
        internal static string spVentaInsertar {
            get {
                return ResourceManager.GetString("spVentaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uspVentaConsultar.
        /// </summary>
        internal static string uspVentaConsultar {
            get {
                return ResourceManager.GetString("uspVentaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uspVentaDetalleConsultar.
        /// </summary>
        internal static string uspVentaDetalleConsultar {
            get {
                return ResourceManager.GetString("uspVentaDetalleConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uspVentaEliminar.
        /// </summary>
        internal static string uspVentaEliminar {
            get {
                return ResourceManager.GetString("uspVentaEliminar", resourceCulture);
            }
        }
    }
}
